### PR TITLE
add German translation

### PR DESCRIPTION
**Pull request by Strubbl**

### CODE REVIEW

**Review by starsep — APPROVED** [review]
Thanks for a pull request @Strubbl! I have read it briefly and looks alright.
I am not a German speaker but I understand a bit from high school.

**Comment by Strubbl** [comment]
if there is some better translation here or there, i bet somebody comes up with an improvement. Maybe even myself if use the page with that translation.

**Review by ttomasz — APPROVED** [review]

**Comment by ttomasz** [comment]
Sorry for delay, merging :)

**Comment by ttomasz** [comment]
changes visible on https://dev.openaedmap.org/ (note: the site is in early stages of development and adding AEDs is not functional yet)

**Comment by Strubbl** [comment]
@mcliquid i like your suggestions. I already did a follow-up pull request. Please see #8 where i addressed some of the issues already.
Do you want open a new pull request to improve the translation?

**Comment by Strubbl** [comment]
Yes, sure. Give it a try. And be sure to start from the branch `dev` and not from main.

**Pull request merged**
