### PR TITLE
Translated country tiles

### LINKED ISSUE #145: Use translated vector tiles
New backend allows to use translated vector tiles. It required providing `lang` argument.
TODO: Check whether all languages on frontend are supported on the backend.
Example url: https://backdev.openaedmap.org/api/v1/tile/3/5/3.mvt?lang=PL

### PR DESCRIPTION
**Pull request by starsep**

### CODE REVIEW

**Comment by starsep** [comment]
@Zaczero what do you think about translated country tiles only for zoom levels 3 to 5? 
I know that cache is a concern (https://github.com/openstreetmap-polska/openaedmap-frontend/issues/145#issuecomment-1668721154). Perhaps it's not that bad due to low number of tiles.

I still have to handle fallback for languages which aren't supported on the backend. I would rather add fallback in the backend code: English names when we don't have names for given `lang` argument.

**Comment by ttomasz** [comment]
I think it would be best for backend to serve all available languages in every tile without this dynamic parameter. Then they would be cached properly and size increase should be insignificant.

**Comment by Zaczero** [comment]
I agree with the translated tiles being available just for country tiles (low zoom levels). But the logic for deciding whether to request translated tiles should be included in the frontend, so it uses 1 set of parameters for low zooms, and 2nd set of parameters for high zooms. I don't think there is a way to do it entirely on backend.

**Comment by Zaczero** [comment]
On the other hand, how about backend always return complete country metadata for tiles (incl. translations) and frontend will simply decide which label to set dynamically. It would be a cleaner solution and always rely on a single cache (single request url schema). It can be resolved with a small preprocessing method that runs after downloading of the tiles and before displaying them to the user.

**Comment by starsep** [comment]
> I think it would be best for backend to serve all available languages in every tile without this dynamic parameter. Then they would be cached properly and size increase should be insignificant.

Sensible alternative. We would have to check what actual size increase it is.
Note that `lang` parameter is already implemented on the backend.

> I agree with the translated tiles being available just for country tiles (low zoom levels). But the logic for deciding whether to request translated tiles should be included in the frontend, so it uses 1 set of parameters for low zooms, and 2nd set of parameters for high zooms. I don't think there is a way to do it entirely on backend.

It's already implemented in this PR: https://github.com/openstreetmap-polska/openaedmap-frontend/pull/186/files#diff-c7b2fcb42edb5d14abc0625a894f3cd531be53cf689a2683fd9cf26cb0ddd74cR23-R35

**Comment by Zaczero** [comment]
I updated backend to return complete country translation info in tiles

**Comment by starsep** [comment]
@Zaczero Unfortunately backend doesn't seem to return translated `country_names`. 
I think it's because it is `dict` in Python.
I can comment out this line and result is the same
https://github.com/openstreetmap-polska/openaedmap-backend/blob/e651bc569c33c6206b0f2f993deb0e17ff1c5b59/api/v1/tile.py#L106

Example:
> npx @mapbox/vt2geojson "http://127.0.0.1:8000/api/v1/tile/4/8/5.mvt" | jq '.features[40].properties'

```
{
  "country_name": "Vatican City",
  "country_code": "VA",
  "point_count": 1,
  "point_count_abbreviated": "1",
  "vt_layer": "defibrillators"
}
```

Size is the same (in bytes):
`http "http://127.0.0.1:8000/api/v1/tile/4/8/5.mvt" | wc -c`
> 21934


After adding on the backend
``` Python
**{
  f'country_name_{key}': value
  for key, value in country.names.items()
}
```

I see expected data
```
[...]
  "country_name_default": "Vatican City",
  "country_name_ACE": "Vatikan",
  "country_name_AF": "Vatikaanstad",
  "country_name_ALS": "Vatikan",
  "country_name_AM": "ቫቲካን ከተማ",
  "country_name_AN": "Ciudat d'o Vaticano",
  "country_name_ANG": "Faticanburg",
  "country_name_AR": "الفاتيكان",
  "country_name_ARC": "ܡܕܝܢܬܐ ܕܘܛܝܩܢ",
[...]
```

But increase in size is significant: 21.9 kB-> 141.8 kB. Gzipped 19.2kB -> 86kB
We could optimize keys used or pack in some array perhaps but still translated names are large themselves.

I would rather just stay with `lang` parameter solution.
What do you think?

**Comment by Zaczero** [comment]
Maybe MVT encoder does not support dict values? Weird, I'll check it. We could make a separate endpoint to retrieve a list of countries and their translations. This would result in just 1 request that is somewhat big in size. But the frontend logic will be more complex. I personally don't think 60kb is a significant amount of data today.

**Comment by Zaczero** [comment]
Also, we already have country name translations on the geojson download panel. Is it possible to reuse that system instead?

**Comment by starsep** [comment]
> Also, we already have country name translations on the geojson download panel. Is it possible to reuse that system instead?

That's good idea. I can use translated country names from data export. I will use `country_code` AS key. Let's keep `county_name` in vector tiles as fallback.

> I personally don't think 60kb is a significant amount of data today.

Note that it's 60kB per 3-5 zoom vector tile. I agree it's not much if done once per user

**Comment by ttomasz** [comment]
> > I personally don't think 60kb is a significant amount of data today.
> 
> Note that it's 60kB per 3-5 zoom vector tile. I agree it's not much if done once per user

From what I have checked for low level zoom tiles on current openaedmap.org png tiles from background map are around 4-5 larger than current vector tiles with countries data. Given the numbers that you provided it seems that adding all languages would lead to tiles being similar size to openstreetmap png tiles. 200-400kb of data per screen instead of 50-100kb is imo still small enough difference.

**Comment by starsep** [comment]
I wrote support for using country names from data export.

App seems sluggish. I will have to test it at home. 
I don't know whether it's actual performance issue I can mitigate. I suspect dynamic map style might cause it.
I am using a laptop in a train atm.

Translated country names for Polish:
image

**Comment by Zaczero** [comment]
I have some experience with using the browser profiler, perhaps push it on dev for me to test?

**Comment by starsep** [comment]
Merged. I will definitely test it myself on dev before deploying to prod :)

**Comment by starsep** [comment]
Merged. I will definitely test it myself on dev before deploying to prod :)

**Comment by Zaczero** [comment]
I don't notice any slowdowns after the names load in. There is a small delay at the beginning when names request is pending. I have noticed it is sent with "normal" priority, perhaps hint it to high priority: fetch('https://example.com/', {priority: 'high'}).

**Pull request merged**
