### PR TITLE
Colour repair to GitHub button

### PR DESCRIPTION
**Pull request by Coolawik**

### CODE REVIEW

**Comment by ttomasz** [comment]
@Coolawik merge to dev first ;)

**Comment by ttomasz** [comment]
Also i'd prefer to keep urls to be anchors instead of buttons since this works nicely with the browser. It opens url in new tab. On right click context menu has options to copy the url, open it in new tab, window etc.

**Comment by Coolawik** [comment]
@ttomasz Oh, ok. But what does that it change when I merges to dev first?

**Comment by ttomasz** [comment]
It deploys to dev.openaedmap.org

**Comment by Coolawik** [comment]
O! Thanks for that advice!

**Pull request merged**
