### PR TITLE
made the logo clickable

### PR DESCRIPTION
**Pull request by shubhamku044**

### CODE REVIEW

**Comment by shubhamku044** [comment]
#157

**Comment by starsep** [comment]
Thanks for your first contribution!

Unfortunately adding link in such simple way changes how navbar is rendered

Before
image
After
image

**Comment by Zaczero** [comment]
Adding a simple `display:flex` CSS fixes the display.

image

**Comment by shubhamku044** [comment]
Ok will do this. Actually I was not able to run the application locally. I tried both the ways, by running it in docker and by running directly on my machine. But both didn't worked out for me. So I didn't saw something broke after adding the anchor tag.

**Comment by Zaczero** [comment]
@shubhamku044 
https://github.com/openstreetmap-polska/openaedmap-frontend#local-environment
Those instructions worked for me last time

**Comment by ttomasz** [comment]
I changed `Navbar.Item renderAs="div"` to `Navbar.Item renderAs="a" href...` and it seems to maintain formatting.

I tested it running from Github Codespace which is another option to open the project.

**Pull request merged**
